export const IPC_CHANNELS = {
  app: {
    isPackaged: "app:is-packaged",
    isAdmin: "app:is-admin",
  },
  window: {
    close: "window:close",
    minimize: "window:minimize",
    maximize: "window:maximize",
    isMaximized: "window:is-maximized",
    maximizedChange: "window:maximized-change",
  },
  settings: {
    get: "settings:get",
    save: "settings:save",
    getAdmin: "settings:get-admin",
    setAdmin: "settings:set-admin",
    getAutoStart: "settings:get-auto-start",
    setAutoStart: "settings:set-auto-start",
    getSidebar: "settings:get-sidebar",
    setSidebar: "settings:set-sidebar",
    getZoom: "settings:get-zoom",
    setZoom: "settings:set-zoom",
    updated: "settings:updated",
  },
  tasks: {
    save: "tasks:save",
    getAll: "tasks:get-all",
    update: "tasks:update",
    run: "tasks:run",
    delete: "tasks:delete",
    export: "tasks:export",
    import: "tasks:import",
    saveBulk: "tasks:save-bulk",
    openDialog: "dialog:open",
    openExceptionDialog: "dialog:open-exception",
  },
  updater: {
    check: "updater:check",
    download: "updater:download",
    install: "updater:install",
    ipc: {
      available: "updater:available",
      notAvailable: "updater:not-available",
      progress: "updater:progress",
      downloaded: "updater:downloaded",
      error: "updater:error",
    },
    events: {
      available: "update-available",
      notAvailable: "update-not-available",
      progress: "download-progress",
      downloaded: "update-downloaded",
      error: "error",
    },
  },
} as const;
